engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - "**.js"
exclude_paths:
- .storybook/
- build/
- config/
- node_modules/
- public/
- scripts/
- stories/
- src/components/**/*.stories.js
- src/App.js
- src/Egeo.js

